### ISSUE TITLE
Make target dependencies possible

### ISSUE THREAD

**Issue by rtuin** [rtuin/pla#1]
I'm thinking of the following format:

``` yaml
# Plafile.yml
all:
  - @test
  - @build
test:
  # tests commands here
build:
  # build commands here
```
